### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=KbG3Hl&redirect_uri=http://www.51xuecheng.cn


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=t1&password=111111

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIzLTA1LTMwVDIyOjE5OjU2XCIsXCJpZFwiOlwiZTU4NjUzMWYtZGVjMC00MzRlLWI1M2ItMzQ3NjNlNTRkZjM5XCIsXCJuYW1lXCI6XCLlh4nlrZBcIixcIm5pY2tuYW1lXCI6XCLlh4nlrZBcIixcInBlcm1pc3Npb25zXCI6W10sXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJvV2dHejFGNlYxR2Y2a2YtUV8ybWlJYTlBdEdFXCIsXCJ1dHlwZVwiOlwiMTAxMDAxXCIsXCJ3eFVuaW9uaWRcIjpcIm9XZ0d6MUY2VjFHZjZrZi1RXzJtaUlhOUF0R0VcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjg1NDk5NjYxLCJhdXRob3JpdGllcyI6WyJ4Y19zeXNtYW5hZ2VyX2RvYyIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfbGlzdCIsInhjX3N5c21hbmFnZXIiLCJ4Y19zeXNtYW5hZ2VyX2NvbXBhbnkiLCJ4Y19zeXNtYW5hZ2VyX2xvZyJdLCJqdGkiOiJiNzBjZDI0OS01NmNkLTQ4ZDYtYTlhNS1mMTQ1YTVkZDlmMjciLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.dMHrhgrX31vcysHlAD6ZO8xb6gkOJBByEKj0rhjltU0


### 密码模式，请求AuthParamsDto参数
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"t1","password":"111111","authType":"password"}

